# Generated by Django 5.2.8 on 2025-11-23 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchers',
            field=models.ManyToManyField(related_name='listings_watched', through='auctions.Watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
